<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-10-24 15:45

$extensionPath = t3lib_extMgm::extPath('pnf_extend_comments');
return array(
	'tx_pnfcommentsscheduler_helper' => $extensionPath . 'scheduler/class.tx_pnfcommentsscheduler_helper.php',
	'tx_pnfcommentsscheduler_scheduler' => $extensionPath . 'scheduler/class.tx_pnfcommentsscheduler_scheduler.php',
);
?>